channels:
  - nvidia
  - pytorch
  - conda-forge
  - r
  - defaults
dependencies:
  - einops
  - h11
  - httpcore
  - huggingface::datasets
  - huggingface::transformers
  - ipykernel
  - ipywidgets
  - jaxtyping
  - numpy
  - plotly
  - protobuf
  - pynvml
  - pytorch=2.0.*
  - pytorch-cuda=11.8
  - scikit-learn
  - sentencepiece
  - simple-parsing
  - torchvision 
  - torchaudio
  - tqdm
  - python=3.10
  - git
  - pip
  - pip:
    - circuitsvis
    - git+https://github.com/neelnanda-io/TransformerLens
    - "-e lib/elk"
