name: dlkworks
channels:
  - conda-forge
  - pytorch
  - r
  - defaults
dependencies:
  - ipykernel=6.19.2
  - numpy=1.25.0
  - pytorch=2.0.1
  - protobuf=3.20
  - pynvml
  - einops=0.6.1
  - ipywidgets
  - tqdm
  - scikit-learn=1.2.2
  - simple-parsing=0.1.3
  - plotly=5.14.1
  - datasets=2.13.1
  - sentencepiece
  - python==3.10
  - git
  - pip=23.2.1
  - pip:
    - circuitsvis
    - transformer_lens
    - "--editable=lib/elk"
