channels:
  - pytorch
  - conda-forge
  - r
  - defaults
dependencies:
  - einops
  - huggingface::datasets
  - huggingface::transformers>=4.10.*
  - ipykernel
  - ipywidgets
  - jaxtyping
  - numpy
  - plotly
  - protobuf
  - pynvml
  - pytorch
  - scikit-learn
  - sentencepiece
  - simple-parsing
  - torchvision 
  - torchaudio
  - tokenizers>=0.13.3
  - tqdm
  - python
  - git
  - pip
  - pip:
    - circuitsvis
    - git+https://github.com/neelnanda-io/TransformerLens
    - "-e lib/elk"
