channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - ipykernel
  - numpy
  - pytorch::pytorch
  - protobuf
  - pynvml
  - einops
  - ipywidgets
  - tqdm
  - scikit-learn
  - simple-parsing
  - plotly
  - huggingface::datasets
  - sentencepiece
  - huggingface::transformers
  - jaxtyping
  - python
  - git
  - pip
  - pip:
    - circuitsvis
    - transformer_lens
    - "-e lib/elk"
